name: CI

on: [push, pull_request]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.46.0
    steps:
      - uses: actions/checkout@v4
      - name: SwiftLint
        run: swiftlint --strict

  macOS:
    runs-on: macos-12
    env:
      XCODE_VERSION: ${{ '14.1' }}
    steps:
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Run
        run: rake build[release]
      - name: Test
        run: rake test

  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test
