name: release_binaries
on:
  release:
    types: created

jobs:
  macOS:
    name: Add macOS binaries to release
    runs-on: macos-12
    steps:
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_14.1.app"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build x86_64
        run: |
          swift build -c release --arch x86_64
          zip -j XCLogParser-macOS-x86_64-${{github.ref_name}}.zip .build/x86_64-apple-macosx/release/xclogparser

      - name: Build arm64
        run: |
          swift build -c release --arch arm64
          zip -j XCLogParser-macOS-arm64-$TAG_NAME.zip .build/arm64-apple-macosx/release/xclogparser

      - name: Build universal
        run: |
          swift build -c release --arch arm64 --arch x86_64
          zip -j XCLogParser-macOS-x86-64-arm64-$TAG_NAME.zip .build/apple/Products/Release/xclogparser

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true


  linux:
    name: Add Linux binaries to release
    runs-on: ubuntu-latest
    container:
      image: swift:5.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip
        run: apt update && apt install -y zip

      - name: Build Dynamically Linked Binary # Requires Swift to be installed
        run: |
          swift build -c release
          zip -j XCLogParser-linux-amd64-${{github.ref_name}}.zip .build/release/xclogparser

      - name: Build Statically Linked Binary # No external dependencies
        run: |
          swift build -c release --static-swift-stdlib
          zip -j XCLogParser-linux-standalone-amd64-${{github.ref_name}}.zip .build/release/xclogparser

      # Publishing
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
